config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,  :controllers => {registrations: 'registrations'}# Important to have this line added to the routes  
  resources :flights
  resources :airports
  root 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
    #from_airport
    has_many :departing_flights, class_name: 'Flight',
    foreign_key: 'from_airport_id'

    #to_airport
    has_many :arriving_flights, class_name: 'Flight',
    foreign_key: 'to_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :user
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :from_airport, class_name: 'Airport'
    belongs_to :to_airport, class_name: 'Airport'
   
    def flight_details
        "Departure date: #{departure_details}
        From: #{from_airport.airport_code}
        TO: #{to_airport.airport_code}
        Flight Code: #{flight_code}"
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = current_user.build
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:references)
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

    def index
        @airports = Airport.all.map{|a| [a.airport_code, a.id]}
        @dates_for_flights = Flight.all.map{|f| [flight_dates(f), f.departure_details]}
        @flight_code_list = Flight.all.map{|f|[f.flight_code,f.flight_code]}

        #implementation of the search
        @search =Flight.ransack(params[:q]) 
        @flights = @search.result.order(departure_details: :asc)

    end

    def show
    end

    private

    def flight_dates(flight)
        flight.departure_details.strftime("%m/%d/%Y")        
    end



end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private 

    def sign_up_params
        params.require(:user).permit(:first_name,:last_name,:email,:password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:first_name,:last_name,:email,:password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :references %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>References</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.references %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>References:</strong>
  <%= @booking.references %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/flights/index.html.erb
<div class="section">
    <div class="container">
        <div class="column is-two-fifths is-offset-one-quarter">     
            <h2 class="title is-1">Select a Flight</h2>

            <%=search_form_for @search, url: flights_path do |f|%>
                Flight code:
                <%=f.select :flight_code_eq, options_for_select(@flight_code_list), include_blank: true%> <br>
                Flight date:
                <%=f.select :departure_details_eq, options_for_select(@dates_for_flights), include_blank: true%> <br>
                From:
                <%= f.select :from_airport_id_eq, options_for_select(@airports), include_blank: true%> <br>
                To:
                <%= f.select :to_airport_id_eq, options_for_select(@airports), include_blank: true%> <br>
                

                <%= f.submit "Search"%>
            <% end %>
        
           
        </div>
    </div>
</div>

<hr>

<div class="section">
    <%= simple_form_for :query, url: new_booking_path, method: :get do |f|%>
    <div class="container">
        <div class="column is-two-fifths is-offset-one-quarter">
                    <div class="field">
                        <div class="control">
                            <%= f.input :select_a_flight, as: :radio_buttons, collection: @flights,
                             label_method: :flight_details, value_method: :id, wrapper: false, label_html: {class: 'label'},
                             prompt: 'Select your Flight:' %>
                        </div>
                    </div>

        </div>
    </div>
    <div class="container">
        <div class="column is-two-fifths is-offset-one-quarter">
                <div class="field">
                    <div class="control">
                        <%=f.input :number_of_tickets, collection: 1..4,
                         input_html: {class: "input"}, wrapper: false, label_html: {class: 'label'}%>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <%=f.button :submit, 'Book Flight', class: 'button is-medium'%>
                    </div>
                </div>
        </div>
    </div>

    
    <% end %>
</div>




<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"> <%=notice%></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%=alert%></p>
      </div>
    <% end %>
    
    <section class="hero is-link">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to image_tag("https://bulma.io/images/bulma-type-white.png"), root_path, class: "navbar-item" %>

          <span class="navbar-burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
          <%= link_to 'Home', root_path, class: "navbar-item is-active" %>

            <% if user_signed_in? %>
              
                <%= link_to "#{current_user.first_name}'s Info", edit_user_registration_path, class: 'navbar-item'%>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-item' %>

             
              <% else %>
                  <%= link_to 'Sign In', new_user_session_path, class: 'navbar-item' %>
                  <%= link_to 'Sign Up', new_user_registration_path, class: 'navbar-item' %>


              <a class="navbar-item">
                Documentation
              </a>
              <span class="navbar-item">
                <a class="button is-info is-inverted">
                  <span class="icon">
                    <i class="fab fa-github"></i>
                  </span>
                  <span>Download</span>
                </a>
              </span>

            </div>
            <% end %>
        </div>
      </div>
    </nav>
  </div>
  </section>

    <%= yield %>
  </body>
</html>